### ISSUE TITLE
change to real json

### ISSUE THREAD

**Issue by roelmeijer** [mackenly/PyATEMAPI#19]
Is it possible to change de return json? Now I get a False instead of false. And I get a ' instead of "

for example:
from: {'source': 1, 'preview': False, 'program': False}
to: {"source": 1, "preview": false, "program": false}

**Comment by mackenly** [comment]
@roelmeijer Should be fixed in #20. I won't be near an ATEM for a few weeks, so can't test to verify. Ping me if the issue remains. Thanks!
