### ISSUE TITLE
Create a docker image.

### ISSUE THREAD

**Issue by nuvious** [mackenly/PyATEMAPI#48]
Would like to create a docker image. Will submit a PR for one myself with docker/kubernetes deployment examples. I'm a homelab nerd so most of my container stuff is running in docker on kubernetes now so figured I'd take the work that I've been doing and incorporate it.

Again, PR to come.

**Comment by mackenly** [comment]
@nuvious Are you going to host an image on your own Docker account and want to link to it from here, use GitHub packages, or would you like me to host the image on my Docker (with continuous delivery via actions)? Either way is a welcomed contribution!

**Comment by nuvious** [comment]
I can provide github actions to build the image as a part of the pull request. I've done it for some other projects of my own in the past. Will try to set it up to read the version from the python package structure and trigger on changes to the main branch. Alternatively could just go by git tags which is easier but involves some duplication of effort when updating the python version and image version.

**Comment by nuvious** [comment]
@mackenly, PR is opened and I have added some comments ahead of time to highlight points of interest. Feel free to comment and/or ask questions in the PR and I'll answer questions and modify my implementation as needed. Standing by for any questions.
