### ISSUE TITLE
Timetable for media upload

### ISSUE THREAD

**Issue by triwav** [mackenly/PyATEMAPI#50]
Hello. I'm trying to create a simple way to create a simple graphic and push it up to the ATEM media pool. I can handle the graphics side but need help on the pushing to the ATEM side. I was wondering if you had any idea on timetable for adding the media upload capability? I'm a programmer myself and so might be able to be of some assistance although I have very little knowledge in Python. Thank you.

**Comment by mackenly** [comment]
Hi @triwav ! I added that originally hoping that [this issue](https://github.com/clvLabs/PyATEMMax/issues/20) would add support to the underlying package that this project relies on to communicate with ATEMs (PyATEMMax). Unfortunately, it seems to have gone stale. I'm not much of a C++ programmer (which IIRC is what would be needed to add that functionality).

If I recall, the SDKs from Blackmagic include an example for managing the media pool. Alternatively, something like [this CLI tool could probably be rigged up to work](https://github.com/mintopia/atemlib).

Wish I had a better answer for you, but hope that can give a few leads to look into.

**Comment by triwav** [comment]
Thanks @mackenly. I had started looking at the Blackmagic examples as I need it to work on a Mac and that CLI is windows only. Originally it wasn't working for me but finally was able to find files that it would work on so will keep messing with the example they provided and see if I can't figure it out. Thanks for your response.
