### ISSUE TITLE
Please add option to REMOVE passphrase requirement

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mackenly/PyATEMAPI#73]
Please add option to REMOVE passphrase requirement.  We have a use case where the device that will query the server has no ability to provide a passphrase, and we have no need for a passphrase.  Our ATEM switcher is on private network and thus passphrase is not needed.

**Comment by mackenly** [comment]
@Jibun-no-Kage Seems like a good idea to me. Merging the change. It should get pushed out to Docker Hub tomorrow.

**Comment by Jibun-no-Kage** [comment]
Thank you!
