### ISSUE TITLE
Feature Request:  Provide for port assignment via environment variable and/or command line argument?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mackenly/PyATEMAPI#75]
Feature Request:  Provide for port assignment via environment variable and/or command line argument?  Since we run multiple 'listeners' for each of our ATEMs, the micro controller that queries the REST API, knows to jump to each switcher until it finds the one online.

So. keeping things simple, I setup 3 'listeners' started by cron on reboot on our server, but could have used docker of course.

```
@reboot /usr/bin/python3 /root/PyATEMAPI/server.py --ip 192.168.1.102 --passphrase password --port 52000
@reboot /usr/bin/python3 /root/PyATEMAPI/server.py --ip 192.168.1.103 --passphrase password --port 52001
@reboot /usr/bin/python3 /root/PyATEMAPI/server.py --ip 192.168.1.104 --passphrase password --port 52002
```
I have yet to pull the updated code, to ignore the passphrase, will do that this week some time.  At some point I will likely make the listener start up a bit smarter, and stop or start listeners based on what is pingable.  For now this works.

I also added to the server.py script to argparse the port parameter, and check for environment variable for same.  I will not document the changes here... like 3 lines of code, but I am sure you get the gist of the add/changes.  No port provided, defaults to 5555 of course.

By the way, it is a best practice to only use port numbers above 50000 for localized custom solutions, hence I used 52000 range above.  You might want to change the default to something in the 50000 range rather than 5555.  Anything below 1024 is restricted, anything above 1024 to 49999 maybe granted or reserved with the IANA, though not enforced per se.  Worked for a fortune 10 as an enterprise engineer, we had 100,000s of servers, and you would be surprised how often we found port duplicates between 1025 and 49999, never mind developers and vendors using ports below 1024 that were reserved.  I know it sounds a bit nuts... but it happened!

Also, thanks again, your solution was exactly what I needed with I needed it!

**Comment by mackenly** [comment]
@Jibun-no-Kage Yeah I'm not opposed to adding the option and agree with your use case. However, I'm not going to change the default port since that would break anyone currently using it.

**Comment by Jibun-no-Kage** [comment]
Good point.

**Comment by mackenly** [comment]
I've added this feature. It should get picked up by Docker on Monday morning.
